import type { GameConfig } from '../config';
import { randInt, randRange } from '../core/rng';

export interface PatternEntry {
  /** Distance in px after the previous obstacle. */
  gap: number;
  /** Obstacle sprite type 1..6. */
  type: number;
}

export interface ObstaclePattern {
  seed: number;
  entries: PatternEntry[];
}

export interface SpawnDecision {
  type: number;
}

/**
 * Distance-based obstacle spawner.
 *
 * Runs in one of two modes:
 * - `random`: gaps drawn uniformly from [minGapPx, maxGapPx] via an injected RNG
 * - `pattern`: gaps/types replayed from a deterministic pattern (looping) —
 *   generated by scripts/gen_obstacles.py
 */
export class Spawner {
  private distanceSinceLast = 0;
  private patternIndex = 0;
  private nextGap: number;
  private nextType: number;

  constructor(
    private readonly cfg: GameConfig,
    private readonly rng: () => number,
    private readonly pattern?: ObstaclePattern,
  ) {
    const first = this.peekNext();
    this.nextGap = first.gap;
    this.nextType = first.type;
  }

  private peekNext(): PatternEntry {
    if (this.pattern && this.pattern.entries.length > 0) {
      const entry = this.pattern.entries[this.patternIndex % this.pattern.entries.length];
      this.patternIndex += 1;
      // entries.length > 0 makes the modulo index always valid
      return entry as PatternEntry;
    }
    return {
      gap: randRange(this.rng, this.cfg.spawn.minGapPx, this.cfg.spawn.maxGapPx),
      type: randInt(this.rng, 1, Object.keys(this.cfg.obstacles.sizes).length),
    };
  }

  /**
   * Advance by the distance the world scrolled this step.
   * Returns a spawn decision when the pending gap has been covered.
   */
  advance(distanceDelta: number): SpawnDecision | null {
    this.distanceSinceLast += distanceDelta;
    if (this.distanceSinceLast < this.nextGap) return null;
    const type = this.nextType;
    this.distanceSinceLast -= this.nextGap;
    const next = this.peekNext();
    this.nextGap = next.gap;
    this.nextType = next.type;
    return { type };
  }

  reset(): void {
    this.distanceSinceLast = 0;
    this.patternIndex = 0;
    const first = this.peekNext();
    this.nextGap = first.gap;
    this.nextType = first.type;
  }
}
